School 19 create schema part 1
huynhhuuloc129/CT250-Server pull request #2
Opened 2023-09-19 05:38 UTC by Dusthuynh

2023-09-21 22:11 UTC, tulehuynhnhat approved these changes, later dismissed

2023-09-21 22:11 UTC, tulehuynhnhat commented on src/shared/enums/common.enum.ts
Should located in its resources

2023-09-22 03:40 UTC, Dusthuynh commented on src/shared/enums/common.enum.ts
Yes, that's right. However, all the Entity have not yet been agreed upon and completed, so I cannot resolve this issue right now. I will resolve it later.

2023-09-22 04:04 UTC, huynhhuuloc129 requested changes

2023-09-22 04:04 UTC, huynhhuuloc129 commented on src/modules/rooming-subscription-requests/entities/rooming-subscription-request.entity.ts
> +
Missing "State" column

2023-09-24 07:04 UTC, huynhhuuloc129 requested changes

2023-09-24 07:04 UTC, huynhhuuloc129 commented on src/modules/rooms/entities/room.entity.ts
> +	roomID: string;
Remove RoomID

2023-09-24 07:08 UTC, huynhhuuloc129 requested changes

2023-09-24 07:08 UTC, huynhhuuloc129 commented on src/modules/payment-records/entities/payment-record.entity.ts
> +
Add `month, year` column

2023-09-24 07:08 UTC, huynhhuuloc129 commented on src/modules/rooms/entities/room.entity.ts
> +
Missing `width, height` column

2023-09-24 07:20 UTC, Dusthuynh commented on src/modules/rooming-subscription-requests/entities/rooming-subscription-request.entity.ts
> +
line 42

2023-09-24 07:22 UTC, huynhhuuloc129 commented on src/modules/rooming-subscription-requests/entities/rooming-subscription-request.entity.ts
> +
?

2023-10-02 02:37 UTC, tulehuynhnhat approved these changes

2023-10-02 02:38 UTC, huynhhuuloc129 approved these changes

2023-10-02 02:38 UTC, merged